name: Preview docs

on:
  pull_request:
jobs:
  main:
    if: github.repository == 'mlflow/mlflow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install requests
      - name: Create preview link
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python dev/preview_docs.py --ref ${{ github.event.pull_request.head.sha }} --issue-number ${{ github.event.pull_request.number }}
