name: Update requirements

on:
  pull_request:
    paths:
      - requirements/**
  schedule:
    - cron: '0 13 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  python-skinny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-python
        with:
          python-version: '3.8'

      - name: Install dev script dependencies
        run: |
          pip install -r dev/requirements.txt

      - uses: ./.github/actions/update-requirements
        with:
          requirements-yaml-location: requirements/skinny-requirements.yaml
          requirements-txt-output-location: requirements/skinny-requirements.txt

      - name: Install dependencies
        env:
          INSTALL_SKINNY_PYTHON_DEPS: true
          MLFLOW_SKINNY: true
        run: |
          source ./dev/install-common-deps.sh

      - name: Run tests
        run: |
          ./dev/run-python-skinny-tests.sh

  python-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-python
        with:
          python-version: '3.8'
      - uses: ./.github/actions/setup-pyenv
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Install dev script dependencies
        run: |
          pip install -r dev/requirements.txt

      - uses: ./.github/actions/update-requirements
        with:
          requirements-yaml-location: requirements/core-requirements.yaml
          requirements-txt-output-location: requirements/core-requirements.txt

      - name: Install dependencies
        if: steps.update-requirements.outputs.updated == 'true'
        env:
          INSTALL_ML_DEPENDENCIES: true
        run: |
          source ./dev/install-common-deps.sh

      - name: Run tests
        if: steps.update-requirements.outputs.updated == 'true'
        env:
          # Fix for https://github.com/mlflow/mlflow/issues/4229
          SPARK_LOCAL_IP: 127.0.0.1
        run: |
          source dev/setup-ssh.sh
          ./dev/run-python-tests.sh
